package MainFolder;

import Materials.Clock2d;
import Materials.Diem3D;
import Materials.HinhHopChuNhat;
import Materials.HinhTru;
import Shape2D.DoiXungConRan2D;
import Shape2D.Truc2DCuaHuyen;
import Shape2D.MangLuoi2D_VeConRanVersion1;
import static Shape2D.MangLuoi2D_VeConRanVersion1.diemAn;
import Shape2D.PanelShowThongSo;
import Shape2D.ThuPhongCaiCay2D;
import Shape2D.XoayConRan2D;
import cars.work;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HUYENKUTE
 */
public class Main extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form Main
     */
    HinhHopChuNhat hinhHopChuNhat = new HinhHopChuNhat();
    HinhTru HinhTru = new HinhTru();

//    private Timer timer;
    Truc2DCuaHuyen truc;
    MangLuoi2D_VeConRanVersion1 snake = new MangLuoi2D_VeConRanVersion1();
    public static boolean AxisVisible = true;
    public static boolean thisIs2D = true;
    public work car;
    public Clock2d clock;

//    TrucToaDo truc = new TrucToaDo();
    public Main() {
        initComponents();
        jPanel3DShape.setVisible(false);
        jPanel2DShape.setVisible(false);
        jRadioButtonMenuItem_Axis.setSelected(true);
        jRadioButtonMenuItem_NonAxis.setSelected(false);
//        car.StopRun();
//        snake.StopRun();
//        jPanelTHUA.setVisible(false);
        addKeyListener(this);// bắt sự kiện bàn phím
        setFocusable(true);// bắt sự kiện bàn phím

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupViewAxis = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2DTitle3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2DShape = new javax.swing.JPanel();
        jPanel2D_ActionPallet = new javax.swing.JPanel();
        jLabel2DTitle = new javax.swing.JLabel();
        jComboBox_2DShape = new javax.swing.JComboBox<>();
        jPanel_BangDieuKhien = new javax.swing.JPanel();
        btn_Right = new javax.swing.JButton();
        btn_Up = new javax.swing.JButton();
        btn_Left = new javax.swing.JButton();
        btn_Down = new javax.swing.JButton();
        btn_Stop = new javax.swing.JButton();
        btn_BatDau = new javax.swing.JButton();
        jpanelBangThongSo = new javax.swing.JPanel();
        jPanel2D_DrawPallet = new javax.swing.JPanel();
        jPanel3DShape = new javax.swing.JPanel();
        jPanel3DPallet = new javax.swing.JPanel();
        jLabel2DTitle1 = new javax.swing.JLabel();
        jComboBox_3DShape = new javax.swing.JComboBox<>();
        jPanel3DPallet2 = new javax.swing.JPanel();
        jLabel2DTitle2 = new javax.swing.JLabel();
        jTextField_Goc_x = new javax.swing.JTextField();
        jLabel2DTitle6 = new javax.swing.JLabel();
        jLabel2DTitle7 = new javax.swing.JLabel();
        jTextField_Goc_y = new javax.swing.JTextField();
        jTextField_rong = new javax.swing.JTextField();
        jTextField_dai = new javax.swing.JTextField();
        jTextField_Goc_z = new javax.swing.JTextField();
        jLabel2DTitle8 = new javax.swing.JLabel();
        jTextField_cao = new javax.swing.JTextField();
        jButton_OK = new javax.swing.JButton();
        jLabel2DTitle9 = new javax.swing.JLabel();
        jLabel2DTitle10 = new javax.swing.JLabel();
        jLabel2DTitle11 = new javax.swing.JLabel();
        jLabel2DTitle12 = new javax.swing.JLabel();
        jPanel3DPallet3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel_ToaDoA1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel_ToaDoB1 = new javax.swing.JLabel();
        jLabel_ToaDoE1 = new javax.swing.JLabel();
        jLabel_ToaDoD1 = new javax.swing.JLabel();
        jLabel_ToaDoF1 = new javax.swing.JLabel();
        jLabel_ToaDoC1 = new javax.swing.JLabel();
        jLabel_ToaDoG1 = new javax.swing.JLabel();
        jLabel_ToaDoH1 = new javax.swing.JLabel();
        jPane2 = new javax.swing.JPanel();
        jMenuMainBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBoSung2D = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jRadioButtonMenuItem_NonAxis = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Axis = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jDialog1.setTitle("Information");
        jDialog1.setBackground(new java.awt.Color(204, 204, 255));
        jDialog1.setMinimumSize(null);
        jDialog1.setModal(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nguyễn Đỗ Yến Chi - N18DCCN022");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lê Thị Thu Hương - N18DCCN088");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nguyễn Thị Thảo Nguyên - N18DCCN133");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nguyễn Thị Thanh Huyền - N18DCCN082");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Châu Văn Hậu - N18DCCN058");

        jLabel2DTitle3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2DTitle3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2DTitle3.setText("--- THÀNH VIÊN NHÓM ---");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("***");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2DTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2DTitle3)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("----[ VẼ HÌNH CƠ BẢN]---- Nhóm 3 ---- Chi-Hậu-Huyền-Nguyên-Hương");

        jPanel2DShape.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2DShape.setPreferredSize(new java.awt.Dimension(1400, 704));

        jPanel2D_ActionPallet.setBackground(new java.awt.Color(102, 0, 255));
        jPanel2D_ActionPallet.setPreferredSize(new java.awt.Dimension(250, 674));

        jLabel2DTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2DTitle.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2DTitle.setText("----  2D SHAPE  ----");

        jComboBox_2DShape.setBackground(new java.awt.Color(204, 255, 255));
        jComboBox_2DShape.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_2DShape.setForeground(new java.awt.Color(102, 0, 204));
        jComboBox_2DShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRÒ CHƠI CON RẮN", "XE DẠO PHỐ", "ĐÔNG HỒ" }));
        jComboBox_2DShape.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_2DShapeItemStateChanged(evt);
            }
        });
        jComboBox_2DShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_2DShapeActionPerformed(evt);
            }
        });

        jPanel_BangDieuKhien.setBackground(new java.awt.Color(153, 153, 255));
        jPanel_BangDieuKhien.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Bảng điều khiển", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btn_Right.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Right.setForeground(new java.awt.Color(204, 0, 0));
        btn_Right.setText("Phải");
        btn_Right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RightActionPerformed(evt);
            }
        });

        btn_Up.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Up.setForeground(new java.awt.Color(204, 0, 0));
        btn_Up.setText("Lên");
        btn_Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpActionPerformed(evt);
            }
        });

        btn_Left.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Left.setForeground(new java.awt.Color(204, 0, 0));
        btn_Left.setText("Trái");
        btn_Left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LeftActionPerformed(evt);
            }
        });

        btn_Down.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Down.setForeground(new java.awt.Color(204, 0, 0));
        btn_Down.setText("Xuống");
        btn_Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DownActionPerformed(evt);
            }
        });

        btn_Stop.setBackground(new java.awt.Color(204, 0, 0));
        btn_Stop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Stop.setForeground(new java.awt.Color(255, 255, 255));
        btn_Stop.setText("Dừng");
        btn_Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BangDieuKhienLayout = new javax.swing.GroupLayout(jPanel_BangDieuKhien);
        jPanel_BangDieuKhien.setLayout(jPanel_BangDieuKhienLayout);
        jPanel_BangDieuKhienLayout.setHorizontalGroup(
            jPanel_BangDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BangDieuKhienLayout.createSequentialGroup()
                .addComponent(btn_Left, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btn_Right, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btn_Stop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_BangDieuKhienLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel_BangDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Up, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Down))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_BangDieuKhienLayout.setVerticalGroup(
            jPanel_BangDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BangDieuKhienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Up, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BangDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Right, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btn_Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Down, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        btn_BatDau.setBackground(new java.awt.Color(204, 255, 204));
        btn_BatDau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_BatDau.setForeground(new java.awt.Color(0, 0, 153));
        btn_BatDau.setText("BAT DAU");
        btn_BatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BatDauActionPerformed(evt);
            }
        });

        jpanelBangThongSo.setBackground(new java.awt.Color(204, 204, 255));
        jpanelBangThongSo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jpanelBangThongSoLayout = new javax.swing.GroupLayout(jpanelBangThongSo);
        jpanelBangThongSo.setLayout(jpanelBangThongSoLayout);
        jpanelBangThongSoLayout.setHorizontalGroup(
            jpanelBangThongSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        jpanelBangThongSoLayout.setVerticalGroup(
            jpanelBangThongSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2D_ActionPalletLayout = new javax.swing.GroupLayout(jPanel2D_ActionPallet);
        jPanel2D_ActionPallet.setLayout(jPanel2D_ActionPalletLayout);
        jPanel2D_ActionPalletLayout.setHorizontalGroup(
            jPanel2D_ActionPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2D_ActionPalletLayout.createSequentialGroup()
                .addGroup(jPanel2D_ActionPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2D_ActionPalletLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2D_ActionPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2DTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_2DShape, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2D_ActionPalletLayout.createSequentialGroup()
                        .addGroup(jPanel2D_ActionPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2D_ActionPalletLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btn_BatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2D_ActionPalletLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel_BangDieuKhien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2D_ActionPalletLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelBangThongSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2D_ActionPalletLayout.setVerticalGroup(
            jPanel2D_ActionPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2D_ActionPalletLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2DTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_2DShape, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_BatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_BangDieuKhien, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelBangThongSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2D_DrawPallet.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2D_DrawPallet.setPreferredSize(new java.awt.Dimension(1104, 674));

        javax.swing.GroupLayout jPanel2D_DrawPalletLayout = new javax.swing.GroupLayout(jPanel2D_DrawPallet);
        jPanel2D_DrawPallet.setLayout(jPanel2D_DrawPalletLayout);
        jPanel2D_DrawPalletLayout.setHorizontalGroup(
            jPanel2D_DrawPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
        );
        jPanel2D_DrawPalletLayout.setVerticalGroup(
            jPanel2D_DrawPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2DShapeLayout = new javax.swing.GroupLayout(jPanel2DShape);
        jPanel2DShape.setLayout(jPanel2DShapeLayout);
        jPanel2DShapeLayout.setHorizontalGroup(
            jPanel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2DShapeLayout.createSequentialGroup()
                .addComponent(jPanel2D_DrawPallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2D_ActionPallet, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2DShapeLayout.setVerticalGroup(
            jPanel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2D_DrawPallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2D_ActionPallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3DShape.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3DShape.setPreferredSize(new java.awt.Dimension(1400, 704));

        jPanel3DPallet.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3DPallet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3DPallet.setPreferredSize(new java.awt.Dimension(248, 674));

        jLabel2DTitle1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2DTitle1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2DTitle1.setText("----  3D SHAPE  ----");

        jComboBox_3DShape.setBackground(new java.awt.Color(255, 255, 204));
        jComboBox_3DShape.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_3DShape.setForeground(new java.awt.Color(0, 153, 153));
        jComboBox_3DShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hình Hộp Chữ Nhật", "Hình trụ" }));
        jComboBox_3DShape.setToolTipText("");
        jComboBox_3DShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_3DShapeActionPerformed(evt);
            }
        });

        jPanel3DPallet2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3DPallet2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 204))); // NOI18N
        jPanel3DPallet2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3DPallet2.setPreferredSize(new java.awt.Dimension(248, 674));

        jLabel2DTitle2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2DTitle2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle2.setText("Tọa độ góc (x; y; z):");

        jTextField_Goc_x.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Goc_x.setForeground(new java.awt.Color(0, 153, 153));
        jTextField_Goc_x.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Goc_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Goc_xActionPerformed(evt);
            }
        });

        jLabel2DTitle6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2DTitle6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle6.setText("Chiều dài");

        jLabel2DTitle7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2DTitle7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle7.setText("Chiều rộng");

        jTextField_Goc_y.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Goc_y.setForeground(new java.awt.Color(0, 153, 153));
        jTextField_Goc_y.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Goc_y.setToolTipText("");

        jTextField_rong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_rong.setForeground(new java.awt.Color(0, 204, 204));
        jTextField_rong.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_dai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_dai.setForeground(new java.awt.Color(0, 204, 204));
        jTextField_dai.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_Goc_z.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Goc_z.setForeground(new java.awt.Color(0, 153, 153));
        jTextField_Goc_z.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2DTitle8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2DTitle8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle8.setText("Chiều cao");

        jTextField_cao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_cao.setForeground(new java.awt.Color(0, 204, 204));
        jTextField_cao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton_OK.setBackground(new java.awt.Color(255, 255, 204));
        jButton_OK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_OK.setForeground(new java.awt.Color(0, 153, 153));
        jButton_OK.setText("OK");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jLabel2DTitle9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2DTitle9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle9.setText("(");

        jLabel2DTitle10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2DTitle10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle10.setText(")");

        jLabel2DTitle11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2DTitle11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle11.setText(";");

        jLabel2DTitle12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2DTitle12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2DTitle12.setText(";");

        javax.swing.GroupLayout jPanel3DPallet2Layout = new javax.swing.GroupLayout(jPanel3DPallet2);
        jPanel3DPallet2.setLayout(jPanel3DPallet2Layout);
        jPanel3DPallet2Layout.setHorizontalGroup(
            jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3DPallet2Layout.createSequentialGroup()
                .addGroup(jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3DPallet2Layout.createSequentialGroup()
                        .addGroup(jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2DTitle7)
                            .addComponent(jLabel2DTitle8)
                            .addComponent(jLabel2DTitle6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_dai, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextField_rong)
                            .addComponent(jTextField_cao)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3DPallet2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2DTitle9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_OK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3DPallet2Layout.createSequentialGroup()
                                .addComponent(jTextField_Goc_x, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2DTitle11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Goc_y, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2DTitle12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Goc_z, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2DTitle10)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel2DTitle2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3DPallet2Layout.setVerticalGroup(
            jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3DPallet2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2DTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Goc_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Goc_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Goc_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2DTitle9)
                    .addComponent(jLabel2DTitle10)
                    .addComponent(jLabel2DTitle11)
                    .addComponent(jLabel2DTitle12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2DTitle6)
                    .addComponent(jTextField_dai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2DTitle7)
                    .addComponent(jTextField_rong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3DPallet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2DTitle8))
                .addGap(18, 18, 18)
                .addComponent(jButton_OK)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel3DPallet3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3DPallet3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông số", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 204))); // NOI18N
        jPanel3DPallet3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3DPallet3.setPreferredSize(new java.awt.Dimension(248, 674));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 204));
        jLabel17.setText("A");

        jLabel_ToaDoA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ToaDoA1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel_ToaDoA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ToaDoA1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 204));
        jLabel18.setText("B");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 204));
        jLabel19.setText("C");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 204));
        jLabel20.setText("D");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 204));
        jLabel21.setText("E");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 204));
        jLabel22.setText("F");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 204));
        jLabel23.setText("G");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 204));
        jLabel24.setText("H");

        jLabel_ToaDoB1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ToaDoB1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel_ToaDoB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ToaDoB1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_ToaDoE1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ToaDoE1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel_ToaDoE1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ToaDoE1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_ToaDoD1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ToaDoD1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel_ToaDoD1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ToaDoD1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_ToaDoF1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ToaDoF1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel_ToaDoF1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ToaDoF1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_ToaDoC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ToaDoC1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel_ToaDoC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ToaDoC1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_ToaDoG1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ToaDoG1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel_ToaDoG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ToaDoG1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_ToaDoH1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ToaDoH1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel_ToaDoH1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ToaDoH1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3DPallet3Layout = new javax.swing.GroupLayout(jPanel3DPallet3);
        jPanel3DPallet3.setLayout(jPanel3DPallet3Layout);
        jPanel3DPallet3Layout.setHorizontalGroup(
            jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3DPallet3Layout.createSequentialGroup()
                .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_ToaDoB1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                            .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_ToaDoA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_ToaDoC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ToaDoG1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ToaDoF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ToaDoE1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ToaDoD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ToaDoH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3DPallet3Layout.setVerticalGroup(
            jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel_ToaDoA1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_ToaDoB1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                        .addComponent(jLabel_ToaDoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_ToaDoD1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel_ToaDoE1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel_ToaDoF1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3DPallet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24))
                    .addGroup(jPanel3DPallet3Layout.createSequentialGroup()
                        .addComponent(jLabel_ToaDoG1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_ToaDoH1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3DPalletLayout = new javax.swing.GroupLayout(jPanel3DPallet);
        jPanel3DPallet.setLayout(jPanel3DPalletLayout);
        jPanel3DPalletLayout.setHorizontalGroup(
            jPanel3DPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3DPalletLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3DPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3DPalletLayout.createSequentialGroup()
                        .addComponent(jPanel3DPallet3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3DPalletLayout.createSequentialGroup()
                        .addGroup(jPanel3DPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3DPallet2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jComboBox_3DShape, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2DTitle1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );
        jPanel3DPalletLayout.setVerticalGroup(
            jPanel3DPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3DPalletLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2DTitle1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_3DShape, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3DPallet3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3DPallet2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPane2.setBackground(new java.awt.Color(153, 204, 255));
        jPane2.setPreferredSize(new java.awt.Dimension(1104, 674));

        javax.swing.GroupLayout jPane2Layout = new javax.swing.GroupLayout(jPane2);
        jPane2.setLayout(jPane2Layout);
        jPane2Layout.setHorizontalGroup(
            jPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
        );
        jPane2Layout.setVerticalGroup(
            jPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3DShapeLayout = new javax.swing.GroupLayout(jPanel3DShape);
        jPanel3DShape.setLayout(jPanel3DShapeLayout);
        jPanel3DShapeLayout.setHorizontalGroup(
            jPanel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3DShapeLayout.createSequentialGroup()
                .addComponent(jPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3DPallet, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3DShapeLayout.setVerticalGroup(
            jPanel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3DShapeLayout.createSequentialGroup()
                .addComponent(jPanel3DPallet, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
            .addComponent(jPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");

        jMenu1.setText("Open ");

        jMenuItem1.setText("2D Shape");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("3D Shape");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBoSung2D.setText("Bổ Sung 2D");

        jMenuItem4.setText("Đối xứng con Rắn");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuBoSung2D.add(jMenuItem4);

        jMenuItem5.setText("Xoay Con Rắn");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuBoSung2D.add(jMenuItem5);

        jMenuItem6.setText("Thu Phóng cái cây");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuBoSung2D.add(jMenuItem6);

        jMenu1.add(jMenuBoSung2D);

        jMenuFile.add(jMenu1);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem3);

        jMenuMainBar.add(jMenuFile);

        jMenuView.setText("View");

        buttonGroupViewAxis.add(jRadioButtonMenuItem_NonAxis);
        jRadioButtonMenuItem_NonAxis.setSelected(true);
        jRadioButtonMenuItem_NonAxis.setText("None Axis");
        jRadioButtonMenuItem_NonAxis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem_NonAxisActionPerformed(evt);
            }
        });
        jMenuView.add(jRadioButtonMenuItem_NonAxis);

        buttonGroupViewAxis.add(jRadioButtonMenuItem_Axis);
        jRadioButtonMenuItem_Axis.setText("Axis");
        jRadioButtonMenuItem_Axis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem_AxisActionPerformed(evt);
            }
        });
        jMenuView.add(jRadioButtonMenuItem_Axis);

        jMenuMainBar.add(jMenuView);

        jMenu4.setText("Information");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuMainBar.add(jMenu4);

        setJMenuBar(jMenuMainBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2DShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3DShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2DShape, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3DShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jPanel2D_DrawPallet.removeAll();
        thisIs2D = true;
        jPanel2DShape.setVisible(true);
        jpanelBangThongSo.removeAll();
        jPanel2DShape.repaint();
        jpanelBangThongSo.repaint();
        jPanel3DShape.setVisible(false);
        jComboBox_2DShape.setSelectedIndex(0);
        if (jRadioButtonMenuItem_Axis.isSelected()) {

            truc = new Truc2DCuaHuyen();
            jPanel2D_DrawPallet.setSize(1102, 672);
            truc.setSize(1102, 672);
            jPanel2D_DrawPallet.add(truc);

        }

        //=============================
        if (jComboBox_2DShape.getSelectedIndex() == 0) {

            PanelShowThongSo Pan = new PanelShowThongSo(0);
            Pan.setSize(236, 270);
            Pan.setLocation(0, 0);
            jpanelBangThongSo.add(Pan);
            Pan.setVisible(true);

        } else if (jComboBox_2DShape.getSelectedIndex() == 1) {

            PanelShowThongSo Pan = new PanelShowThongSo(1);
            Pan.setSize(236, 270);
            Pan.setLocation(0, 0);
            jpanelBangThongSo.add(Pan);
            Pan.setVisible(true);

        }
        jpanelBangThongSo.repaint();
        repaint();


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (thisIs2D) {
            snake.ResetAll();

        }
        jpanelBangThongSo.removeAll();
        jpanelBangThongSo.repaint();
        jPanel2D_DrawPallet.removeAll();
        thisIs2D = false;
        jPanel2DShape.setVisible(false);
        jPanel3DShape.setVisible(true);
        repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    private void btn_RightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RightActionPerformed
        // TODO add your handling code here:
//        jPanel2D_DrawPallet.add(truc);
        snake.snake.QueoPhai();
//        snake.snake.TiepTuc();
//        snake.repaint();
        if (jComboBox_2DShape.getSelectedIndex() == 1) {
            car.moveright();
        }
    }//GEN-LAST:event_btn_RightActionPerformed


    private void btn_UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpActionPerformed
        // TODO add your handling code here:
        snake.snake.QueoLen();
//        snake.snake.TiepTuc();
//        snake.repaint();
        if (jComboBox_2DShape.getSelectedIndex() == 1) {
            car.moveup();
        }

    }//GEN-LAST:event_btn_UpActionPerformed

    private void btn_LeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LeftActionPerformed
        // TODO add your handling code here:
        snake.snake.QueoTrai();

        if (jComboBox_2DShape.getSelectedIndex() == 1) {
            car.moveleft();
        }
//        snake.snake.TiepTuc();
//        snake.repaint();
    }//GEN-LAST:event_btn_LeftActionPerformed

    private void btn_DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DownActionPerformed
        // TODO add your handling code here:
        snake.snake.QueoXuong();
//        snake.snake.TiepTuc();
//        snake.repaint();
        if (jComboBox_2DShape.getSelectedIndex() == 1) {
            car.movedown();
        }
//        snake.repaint();
    }//GEN-LAST:event_btn_DownActionPerformed

    private void btn_StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StopActionPerformed
        // TODO add your handling code here:
        snake.StopRun();
        if (jComboBox_2DShape.getSelectedIndex() == 0) {

            if (snake.trangthai % 2 == 1) {
                btn_Stop.setText("Tiếp tục");
            } else {
                btn_Stop.setText("Dừng");
            }
        } else if (jComboBox_2DShape.getSelectedIndex() == 1) {
            if (car.tieptucdichuyen) {
                car.StopRun();
                btn_Stop.setText("Tiếp tục");
            } else {
                car.Continue();
                btn_Stop.setText("Dừng");
            }
        }


    }//GEN-LAST:event_btn_StopActionPerformed

    private void btn_BatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BatDauActionPerformed
        // TODO add your handling code here:
        diemAn = 0;
        jPanel2D_DrawPallet.removeAll();

        jPanel2DShape.setVisible(true);
        jpanelBangThongSo.removeAll();
        jpanelBangThongSo.repaint();
        if (jComboBox_2DShape.getSelectedIndex() == 1) {
            snake.ResetAll();

            car = new work();
            if (jRadioButtonMenuItem_Axis.isSelected()) {
                car.AxisVisible = true;
            } else {
                car.AxisVisible = false;
            }

            car.setSize(1110, 650);
            jPanel2D_DrawPallet.add(car);
//            car.setVisible(true);
            //car.Continue();
            PanelShowThongSo Pan = new PanelShowThongSo(1);
            Pan.setSize(236, 270);
            Pan.setLocation(0, 0);
            jpanelBangThongSo.add(Pan);
            Pan.setVisible(true);

            jPanel_BangDieuKhien.setVisible(true);
            repaint();
        }
        if (jComboBox_2DShape.getSelectedIndex() == 0) {
            //car.StopRun();
            snake = new MangLuoi2D_VeConRanVersion1();
            jPanel2D_DrawPallet.setSize(1102, 672);
            snake.setLocation(5, 5);
            snake.setSize(1102, 672);
            jPanel2D_DrawPallet.add(snake);

            PanelShowThongSo Pan = new PanelShowThongSo(0);
            Pan.setSize(236, 270);
            Pan.setLocation(0, 0);
            jpanelBangThongSo.add(Pan);
            Pan.setVisible(true);

            jPanel_BangDieuKhien.setVisible(true);
            repaint();

        }


    }//GEN-LAST:event_btn_BatDauActionPerformed

    private void jComboBox_2DShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_2DShapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_2DShapeActionPerformed

    private void jComboBox_2DShapeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_2DShapeItemStateChanged
        // TODO add your handling code here:
        jPanel2D_DrawPallet.removeAll();
        jpanelBangThongSo.removeAll();
        if (jComboBox_2DShape.getSelectedIndex() == 0) {

            if (car != null) {
                car.StopRun();
            }
            snake = new MangLuoi2D_VeConRanVersion1();
            jPanel_BangDieuKhien.setVisible(true);
            btn_BatDau.setVisible(true);
            repaint();
        } else if (jComboBox_2DShape.getSelectedIndex() == 1) {
            snake.ResetAll();
            car = new work();
            car.StopRun();
            car.setSize(1104, 670);
            jPanel2D_DrawPallet.add(car);
            car.setVisible(true);
            jPanel_BangDieuKhien.setVisible(true);
            btn_BatDau.setVisible(true);
            repaint();
        } else if (jComboBox_2DShape.getSelectedIndex() == 2) {
            snake.ResetAll();
            if (car != null) {
                car.StopRun();
            }
            clock = new Clock2d();
            clock.AxisVisible = AxisVisible;
            clock.setSize(1104, 670);
            jPanel2D_DrawPallet.add(clock);
            clock.setVisible(true);
            jPanel_BangDieuKhien.setVisible(false);
            btn_BatDau.setVisible(false);
            PanelShowThongSo Pan = new PanelShowThongSo(2);
            Pan.setSize(236, 290);
            Pan.setLocation(0, 0);
            jpanelBangThongSo.add(Pan);
            Pan.setVisible(true);
            repaint();
        }


    }//GEN-LAST:event_jComboBox_2DShapeItemStateChanged

    private void jRadioButtonMenuItem_NonAxisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_NonAxisActionPerformed
        // TODO add your handling code here:
        AxisVisible = false;
        if (thisIs2D) {

            snake.ResetAll();
            if (jComboBox_2DShape.getSelectedIndex() == 2) {
                jPanel2D_DrawPallet.removeAll();
                clock = new Clock2d();
                clock.AxisVisible = AxisVisible;
                clock.setSize(1104, 670);
                jPanel2D_DrawPallet.add(clock);
                clock.setVisible(true);
            } else {
                jPanel2D_DrawPallet.removeAll();
            }
        }

        if (thisIs2D == false) {
            if (jRadioButtonMenuItem_NonAxis.isSelected()) {
                hinhHopChuNhat.truc = false;
                HinhTru.truc = false;
            } else {
                hinhHopChuNhat.truc = true;
                HinhTru.truc = true;
            }

        }

        repaint();
    }//GEN-LAST:event_jRadioButtonMenuItem_NonAxisActionPerformed

    private void jRadioButtonMenuItem_AxisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_AxisActionPerformed
        // TODO add your handling code here:
        AxisVisible = true;
        if (thisIs2D) {

            if (jComboBox_2DShape.getSelectedIndex() == 2) {

                jPanel2D_DrawPallet.removeAll();
                clock = new Clock2d();
                clock.AxisVisible = AxisVisible;
                clock.setSize(1104, 670);
                jPanel2D_DrawPallet.add(clock);
                clock.setVisible(true);
                clock.AxisVisible = AxisVisible;
            } else {

                jPanel2D_DrawPallet.removeAll();
                snake.ResetAll();
                truc = new Truc2DCuaHuyen();
                jPanel2D_DrawPallet.setSize(1102, 672);
                truc.setSize(1102, 672);
                jPanel2D_DrawPallet.add(truc);
            }

        } else {
            if (jRadioButtonMenuItem_NonAxis.isSelected()) {
                hinhHopChuNhat.truc = false;
                HinhTru.truc = false;
            } else {
                hinhHopChuNhat.truc = true;
                HinhTru.truc = true;
            }
        }
        repaint();
    }//GEN-LAST:event_jRadioButtonMenuItem_AxisActionPerformed

    private void jComboBox_3DShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_3DShapeActionPerformed
        if (jComboBox_3DShape.getSelectedItem().equals("Hình Hộp Chữ Nhật")) {
            jPane2.removeAll();
            jPane2.repaint();
            jLabel2DTitle6.setText("Chiều dài");
            jLabel2DTitle7.setText("Chiều rộng");
            jLabel2DTitle8.setVisible(true);
            jLabel23.setVisible(true);
            jLabel24.setVisible(true);
            jLabel_ToaDoG1.setVisible(true);
            jLabel_ToaDoH1.setVisible(true);
            jTextField_cao.setVisible(true);
            jTextField_Goc_x.setText("");
            jTextField_Goc_y.setText("");
            jTextField_Goc_z.setText("");
            jTextField_cao.setText("");
            jTextField_dai.setText("");
            jTextField_rong.setText("");
            jLabel_ToaDoA1.setText("");
            jLabel_ToaDoB1.setText("");
            jLabel_ToaDoC1.setText("");
            jLabel_ToaDoD1.setText("");
            jLabel_ToaDoE1.setText("");
            jLabel_ToaDoF1.setText("");
            jLabel_ToaDoG1.setText("");
            jLabel_ToaDoH1.setText("");
            // chi cần

        }
        if (jComboBox_3DShape.getSelectedItem().equals("Hình trụ")) {
            jPane2.removeAll();
            jPane2.repaint();
            jLabel2DTitle6.setText("Chiều cao");
            jLabel2DTitle7.setText("Bán kính");
            jLabel2DTitle8.setVisible(false);
            jLabel23.setVisible(false);
            jLabel24.setVisible(false);
            jLabel_ToaDoG1.setVisible(false);
            jLabel_ToaDoH1.setVisible(false);
            jTextField_cao.setVisible(false);
            jTextField_Goc_x.setText("");
            jTextField_Goc_y.setText("");
            jTextField_Goc_z.setText("");
            jTextField_cao.setText("");
            jTextField_dai.setText("");
            jTextField_rong.setText("");
            jLabel_ToaDoA1.setText("");
            jLabel_ToaDoB1.setText("");
            jLabel_ToaDoC1.setText("");
            jLabel_ToaDoD1.setText("");
            jLabel_ToaDoE1.setText("");
            jLabel_ToaDoF1.setText("");
        }
    }//GEN-LAST:event_jComboBox_3DShapeActionPerformed

    private void jTextField_Goc_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Goc_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Goc_xActionPerformed

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed

        //---------------HÌNH HỘP CHỮ NHẬT-------------------------------
        if (jComboBox_3DShape.getSelectedItem().equals("Hình Hộp Chữ Nhật")) {
            //

            if (jTextField_Goc_x.getText().matches("")
                    || jTextField_Goc_y.getText().matches("")
                    || jTextField_Goc_z.getText().matches("")) {
                JOptionPane.showMessageDialog(null, "Tọa độ điểm \nkhông được trống", "Thông báo", JOptionPane.OK_OPTION);

            }
            if (jTextField_cao.getText().matches("")
                    || jTextField_dai.getText().matches("")
                    || jTextField_rong.getText().matches("")) {
                JOptionPane.showMessageDialog(null, "Giá trị không được trống \nNhập lại", "Thông báo", JOptionPane.OK_OPTION);
            }
            if (Integer.parseInt(jTextField_dai.getText()) > 0
                    && Integer.parseInt(jTextField_cao.getText()) > 0
                    && Integer.parseInt(jTextField_rong.getText()) > 0) {
                // vẽ hình hộp chữ nhật ở đây
                jPane2.removeAll();
                int x, y, z;
                int dai, rong, cao;
                x = Integer.parseInt(jTextField_Goc_x.getText());
                y = Integer.parseInt(jTextField_Goc_y.getText());
                z = Integer.parseInt(jTextField_Goc_z.getText());
                dai = Integer.parseInt(jTextField_dai.getText());
                rong = Integer.parseInt(jTextField_rong.getText());
                cao = Integer.parseInt(jTextField_cao.getText());
                Diem3D goc = new Diem3D(x, y, z);

                hinhHopChuNhat.dai = dai;
                hinhHopChuNhat.rong = rong;
                hinhHopChuNhat.cao = cao;
                hinhHopChuNhat.a = goc;
                hinhHopChuNhat.b = new Diem3D(dai + x, y, z);
                hinhHopChuNhat.c = new Diem3D(dai + x, y, rong + z);
                hinhHopChuNhat.d = new Diem3D(x, y, rong + z);
                hinhHopChuNhat.e = new Diem3D(x, cao + y, z);
                hinhHopChuNhat.f = new Diem3D(dai + x, cao + y, z);
                hinhHopChuNhat.g = new Diem3D(dai + x, cao + y, rong + z);
                hinhHopChuNhat.h = new Diem3D(x, cao + y, rong + z);
                jLabel_ToaDoA1.setText(hinhHopChuNhat.a.HienThi());
                jLabel_ToaDoB1.setText(hinhHopChuNhat.b.HienThi());
                jLabel_ToaDoC1.setText(hinhHopChuNhat.c.HienThi());
                jLabel_ToaDoD1.setText(hinhHopChuNhat.d.HienThi());
                jLabel_ToaDoE1.setText(hinhHopChuNhat.e.HienThi());
                jLabel_ToaDoF1.setText(hinhHopChuNhat.f.HienThi());
                jLabel_ToaDoG1.setText(hinhHopChuNhat.g.HienThi());
                jLabel_ToaDoH1.setText(hinhHopChuNhat.h.HienThi());
                if (jRadioButtonMenuItem_NonAxis.isSelected()) {
                    hinhHopChuNhat.truc = false;
                } else {
                    hinhHopChuNhat.truc = true;
                }
                hinhHopChuNhat.setSize(1102, 672);
                jPane2.setSize(1104, 674);
                jPane2.add(hinhHopChuNhat);

            } else {

                JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ \n Yêu cầu: Chiều dài > 0, chiều rộng > 0, chiều cao > 0", "Thông báo", JOptionPane.OK_OPTION);

            }

        } //-----------------HÌNH TRỤ---------------------------
        else if (jComboBox_3DShape.getSelectedItem().equals("Hình trụ")) {
            if (jTextField_Goc_x.getText().matches("")
                    || jTextField_Goc_y.getText().matches("")
                    || jTextField_Goc_z.getText().matches("")) {
                JOptionPane.showMessageDialog(null, "Tọa độ điểm \nkhông được trống", "Thông báo", JOptionPane.OK_OPTION);

            }
            if (jTextField_dai.getText().matches("")
                    || jTextField_rong.getText().matches("")) {
                JOptionPane.showMessageDialog(null, "Giá trị không được trống \nNhập lại", "Thông báo", JOptionPane.OK_OPTION);
            }
            if (Integer.parseInt(jTextField_dai.getText()) > 0
                    && Integer.parseInt(jTextField_rong.getText()) > 0) {
                // vẽ hình trụ ở đây
                jPane2.removeAll();
                int x, y, z;
                int r, cao;
                x = Integer.parseInt(jTextField_Goc_x.getText());
                y = Integer.parseInt(jTextField_Goc_y.getText());
                z = Integer.parseInt(jTextField_Goc_z.getText());
                cao = Integer.parseInt(jTextField_dai.getText());
                r = Integer.parseInt(jTextField_rong.getText());
                Diem3D goc = new Diem3D(x, y, z);

                HinhTru.r = r;

                HinhTru.cao = cao;
                HinhTru.e = goc;
                HinhTru.a = new Diem3D(x - r, y, z);
                HinhTru.b = new Diem3D(x + r, y, z);
                HinhTru.c = new Diem3D(x + r, y + cao, z);
                HinhTru.d = new Diem3D(x - r, y + cao, z);
                HinhTru.f = new Diem3D(x, y + cao, z);
                jLabel_ToaDoA1.setText(HinhTru.a.HienThi());
                jLabel_ToaDoB1.setText(HinhTru.b.HienThi());
                jLabel_ToaDoC1.setText(HinhTru.c.HienThi());
                jLabel_ToaDoD1.setText(HinhTru.d.HienThi());
                jLabel_ToaDoE1.setText(HinhTru.e.HienThi());
                jLabel_ToaDoF1.setText(HinhTru.f.HienThi());
                if (jRadioButtonMenuItem_NonAxis.isSelected()) {
                    HinhTru.truc = false;
                } else {
                    HinhTru.truc = true;
                }
                HinhTru.setSize(1102, 672);
                jPane2.setSize(1104, 674);
                jPane2.add(HinhTru);
                jPane2.repaint();
            } else {

                JOptionPane.showMessageDialog(null, "Giá trị không hợp lệ \n Yêu cầu: Chiều dài > 0, bán kính > 0", "Thông báo", JOptionPane.OK_OPTION);

            }
        }
    }//GEN-LAST:event_jButton_OKActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        jDialog1.setSize(500, 400);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        DoiXungConRan2D frdx =  new DoiXungConRan2D();
        frdx.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        XoayConRan2D frdx =  new XoayConRan2D();
        frdx.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:XoayConRan2D frdx =  new XoayConRan2D();
        ThuPhongCaiCay2D frdx =  new ThuPhongCaiCay2D();
        frdx.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
        int key = e.getKeyCode();
        switch (key) {
            case KeyEvent.VK_UP:
                if (thisIs2D) {
                    if (jComboBox_2DShape.getSelectedIndex() == 0) {
                        snake.snake.QueoLen();
                    } else if (jComboBox_2DShape.getSelectedIndex() == 1) {
                        car.moveup();
                    }
                }
                break;
            case KeyEvent.VK_DOWN:
                if (thisIs2D) {
                    if (jComboBox_2DShape.getSelectedIndex() == 0) {
                        snake.snake.QueoXuong();
                    } else if (jComboBox_2DShape.getSelectedIndex() == 1) {
                        car.movedown();
                    }
                }

                break;
            case KeyEvent.VK_LEFT:
                if (thisIs2D) {
                    if (jComboBox_2DShape.getSelectedIndex() == 0) {
                        snake.snake.QueoTrai();
                    } else if (jComboBox_2DShape.getSelectedIndex() == 1) {
                        car.moveleft();
                    }
                }

                break;
            case KeyEvent.VK_RIGHT:
                if (thisIs2D) {
                    if (jComboBox_2DShape.getSelectedIndex() == 0) {
                        snake.snake.QueoPhai();
                    } else if (jComboBox_2DShape.getSelectedIndex() == 1) {
                        car.moveright();
                    }
                }

                break;
            default: {
            }
        }//throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BatDau;
    private javax.swing.JButton btn_Down;
    private javax.swing.JButton btn_Left;
    private javax.swing.JButton btn_Right;
    private javax.swing.JButton btn_Stop;
    private javax.swing.JButton btn_Up;
    private javax.swing.ButtonGroup buttonGroupViewAxis;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JComboBox<String> jComboBox_2DShape;
    private javax.swing.JComboBox<String> jComboBox_3DShape;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel2DTitle;
    private javax.swing.JLabel jLabel2DTitle1;
    private javax.swing.JLabel jLabel2DTitle10;
    private javax.swing.JLabel jLabel2DTitle11;
    private javax.swing.JLabel jLabel2DTitle12;
    private javax.swing.JLabel jLabel2DTitle2;
    private javax.swing.JLabel jLabel2DTitle3;
    private javax.swing.JLabel jLabel2DTitle6;
    private javax.swing.JLabel jLabel2DTitle7;
    private javax.swing.JLabel jLabel2DTitle8;
    private javax.swing.JLabel jLabel2DTitle9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_ToaDoA1;
    private javax.swing.JLabel jLabel_ToaDoB1;
    private javax.swing.JLabel jLabel_ToaDoC1;
    private javax.swing.JLabel jLabel_ToaDoD1;
    private javax.swing.JLabel jLabel_ToaDoE1;
    private javax.swing.JLabel jLabel_ToaDoF1;
    private javax.swing.JLabel jLabel_ToaDoG1;
    private javax.swing.JLabel jLabel_ToaDoH1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuBoSung2D;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuBar jMenuMainBar;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JPanel jPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2DShape;
    private javax.swing.JPanel jPanel2D_ActionPallet;
    private javax.swing.JPanel jPanel2D_DrawPallet;
    private javax.swing.JPanel jPanel3DPallet;
    private javax.swing.JPanel jPanel3DPallet2;
    private javax.swing.JPanel jPanel3DPallet3;
    private javax.swing.JPanel jPanel3DShape;
    private javax.swing.JPanel jPanel_BangDieuKhien;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Axis;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_NonAxis;
    private javax.swing.JTextField jTextField_Goc_x;
    private javax.swing.JTextField jTextField_Goc_y;
    private javax.swing.JTextField jTextField_Goc_z;
    private javax.swing.JTextField jTextField_cao;
    private javax.swing.JTextField jTextField_dai;
    private javax.swing.JTextField jTextField_rong;
    private javax.swing.JPanel jpanelBangThongSo;
    // End of variables declaration//GEN-END:variables
}
