/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Shape2D;

import Materials.Clock2d;
import cars.work;
import static cars.work.XeSo;
import static cars.work.trees;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author HUYENKUTE
 */
public class PanelShowThongSo extends JPanel implements ActionListener {

    public static int type = 0;
    // 0 - 1- 2 : Ran - Xe -...
    /**
     * Creates new form PanelShowThongSo
     */
    Timer timer;

    public PanelShowThongSo(int typee) {
        
        initComponents();
        jPanel_ThongSoChoiXe.setVisible(false);
        jPanel_Ran.setVisible(true);
        this.type = typee;
        if (type == 0) {
            
            jPanel_ThongSoChoiXe.setVisible(false);
            jPanel_ThongSoDongHo.setVisible(false);
            jPanel_Ran.setVisible(true);
            jLabel_DiemAnDuoc.setText("" + MangLuoi2D_VeConRanVersion1.diemAn);
            jLabel_DauRan.setText("(" + MangLuoi2D_VeConRanVersion1.toadoDauRan.x + ":" + MangLuoi2D_VeConRanVersion1.toadoDauRan.y + ")");
            jLabel_ThucAn.setText("(" + MangLuoi2D_VeConRanVersion1.toadoThucAn.x + ":" + MangLuoi2D_VeConRanVersion1.toadoThucAn.y + ")");
            jLabel_Boom1.setText("(" + MangLuoi2D_VeConRanVersion1.toadoBoom1.x + ":" + MangLuoi2D_VeConRanVersion1.toadoBoom1.y + ")");
            jLabel_Boom2.setText("(" + MangLuoi2D_VeConRanVersion1.toadoBoom2.x + ":" + MangLuoi2D_VeConRanVersion1.toadoBoom2.y + ")");
            jLabel_Boom3.setText("(" + MangLuoi2D_VeConRanVersion1.toadoBoom3.x + ":" + MangLuoi2D_VeConRanVersion1.toadoBoom3.y + ")");      
            
             timer = new Timer(100, this);
        }
        else if(type == 1)
        {
            
            jPanel_Ran.setVisible(false);
            jPanel_ThongSoDongHo.setVisible(false);
            jPanel_ThongSoChoiXe.setVisible(true);
            
            jLabel_Xe.setText("("+(XeSo.x+8)+":"+(XeSo.y-7)+")"); 
            jLabel_Cay1.setText("("+trees[0].x+":"+trees[0].y+")"); 
            jLabel_Cay2.setText("("+trees[1].x+":"+trees[1].y+")"); 
            jLabel_Cay3.setText("("+trees[2].x+":"+trees[2].y+")"); 
            jLabel_Cay4.setText("("+trees[3].x+":"+trees[3].y+")"); 
            jLabel_Cay5.setText("("+trees[5].x+":"+trees[5].y+")"); 
            jLabel_Cay6.setText("("+trees[6].x+":"+trees[6].y+")"); 
            jLabel_Cay7.setText("("+trees[7].x+":"+trees[7].y+")"); 
            jLabel_Cay8.setText("("+trees[8].x+":"+trees[8].y+")");
            timer = new Timer(100, this); 
        }  
        else if(type == 2)
        {
            
            jPanel_Ran.setVisible(false);
            jPanel_ThongSoChoiXe.setVisible(false);
            jPanel_ThongSoDongHo.setVisible(true);
            lbl_TAm.setText("("+(Clock2d.tamDongHo.x)+":"+(Clock2d.tamDongHo.y)+")");
            jLabel_KimGio.setText("("+(Clock2d.kimGio.x)+":"+(Clock2d.kimGio.y)+")");
            jLabel_KimPhut.setText("("+(Clock2d.kimPhut.x)+":"+(Clock2d.kimPhut.y)+")");
            jLabel_KimGiay.setText("("+(Clock2d.kimGiay.x)+":"+(Clock2d.kimGiay.y)+")");
            
            timer = new Timer(1000, this);
        }
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_ThongSoChoiXe = new javax.swing.JPanel();
        jLabel_Xe = new javax.swing.JLabel();
        jLabel_Cay3 = new javax.swing.JLabel();
        jLabel_Cay1 = new javax.swing.JLabel();
        jLabel_Cay4 = new javax.swing.JLabel();
        jLabel_Cay2 = new javax.swing.JLabel();
        jLabel_2 = new javax.swing.JLabel();
        jLabel_3 = new javax.swing.JLabel();
        jLabel_5 = new javax.swing.JLabel();
        jLabel_7 = new javax.swing.JLabel();
        jLabel_Cay7 = new javax.swing.JLabel();
        jLabel_Cay5 = new javax.swing.JLabel();
        jLabel_Cay8 = new javax.swing.JLabel();
        jLabel_Cay6 = new javax.swing.JLabel();
        jLabel_9 = new javax.swing.JLabel();
        jPanel_Ran = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_DauRan = new javax.swing.JLabel();
        jLabel_Boom2 = new javax.swing.JLabel();
        jLabel_ThucAn = new javax.swing.JLabel();
        jLabel_Boom3 = new javax.swing.JLabel();
        jLabel_Boom1 = new javax.swing.JLabel();
        jLabel_01 = new javax.swing.JLabel();
        jLabel_02 = new javax.swing.JLabel();
        jLabel_03 = new javax.swing.JLabel();
        jLabel_04 = new javax.swing.JLabel();
        jLabel_DiemAnDuoc = new javax.swing.JLabel();
        jLabel_05 = new javax.swing.JLabel();
        jPanel_ThongSoDongHo = new javax.swing.JPanel();
        lbl_TAm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_KimGio = new javax.swing.JLabel();
        jLabel_KimPhut = new javax.swing.JLabel();
        jLabel_KimGiay = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng Thông Số", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 102))); // NOI18N
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(236, 270));

        jPanel_ThongSoChoiXe.setBackground(new java.awt.Color(255, 204, 204));
        jPanel_ThongSoChoiXe.setPreferredSize(new java.awt.Dimension(226, 230));

        jLabel_Xe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Xe.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Xe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Xe.setText("(--:--)");

        jLabel_Cay3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Cay3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Cay3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cay3.setText("(--:--)");

        jLabel_Cay1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Cay1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Cay1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cay1.setText("(--:--)");

        jLabel_Cay4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Cay4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Cay4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cay4.setText("(--:--)");

        jLabel_Cay2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Cay2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Cay2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cay2.setText("(--:--)");

        jLabel_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_2.setText("Xe:");

        jLabel_3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_3.setText("Cây1&5:");

        jLabel_5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_5.setText("Cây2&6:");

        jLabel_7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_7.setText("Cây4&8:");

        jLabel_Cay7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Cay7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Cay7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cay7.setText("(--:--)");

        jLabel_Cay5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Cay5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Cay5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cay5.setText("(--:--)");

        jLabel_Cay8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Cay8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Cay8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cay8.setText("(--:--)");

        jLabel_Cay6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Cay6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Cay6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cay6.setText("(--:--)");

        jLabel_9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_9.setText("Cây3&7:");

        javax.swing.GroupLayout jPanel_ThongSoChoiXeLayout = new javax.swing.GroupLayout(jPanel_ThongSoChoiXe);
        jPanel_ThongSoChoiXe.setLayout(jPanel_ThongSoChoiXeLayout);
        jPanel_ThongSoChoiXeLayout.setHorizontalGroup(
            jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongSoChoiXeLayout.createSequentialGroup()
                .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ThongSoChoiXeLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Cay1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Cay3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Cay4, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel_Cay2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_ThongSoChoiXeLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Xe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ThongSoChoiXeLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Cay7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Cay5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Cay6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Cay8, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_ThongSoChoiXeLayout.setVerticalGroup(
            jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongSoChoiXeLayout.createSequentialGroup()
                .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Xe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cay1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cay2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cay3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cay4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cay5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cay6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ThongSoChoiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cay7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cay8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel_Ran.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ĐIỂM:");

        jLabel_DauRan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_DauRan.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_DauRan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_DauRan.setText("(--:--)");

        jLabel_Boom2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Boom2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Boom2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Boom2.setText("(--:--)");

        jLabel_ThucAn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ThucAn.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_ThucAn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ThucAn.setText("(--:--)");

        jLabel_Boom3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Boom3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Boom3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Boom3.setText("(--:--)");

        jLabel_Boom1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Boom1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Boom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Boom1.setText("(--:--)");

        jLabel_01.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_01.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_01.setText("Đầu Rắn:");

        jLabel_02.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_02.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_02.setText("Thức Ăn");

        jLabel_03.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_03.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_03.setText("Boom 1:");

        jLabel_04.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_04.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_04.setText("Boom 2:");

        jLabel_DiemAnDuoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_DiemAnDuoc.setForeground(new java.awt.Color(102, 0, 0));
        jLabel_DiemAnDuoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_DiemAnDuoc.setText("0");

        jLabel_05.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_05.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_05.setText("Boom 3:");

        javax.swing.GroupLayout jPanel_RanLayout = new javax.swing.GroupLayout(jPanel_Ran);
        jPanel_Ran.setLayout(jPanel_RanLayout);
        jPanel_RanLayout.setHorizontalGroup(
            jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RanLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_DiemAnDuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_RanLayout.createSequentialGroup()
                .addGroup(jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_01, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_02, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_03, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_04, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_05, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Boom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Boom2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ThucAn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Boom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_DauRan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_RanLayout.setVerticalGroup(
            jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RanLayout.createSequentialGroup()
                .addGroup(jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DiemAnDuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DauRan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ThucAn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Boom1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Boom2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel_RanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Boom3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel_ThongSoDongHo.setBackground(new java.awt.Color(255, 204, 204));
        jPanel_ThongSoDongHo.setPreferredSize(new java.awt.Dimension(226, 230));

        lbl_TAm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TAm.setForeground(new java.awt.Color(0, 0, 204));
        lbl_TAm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TAm.setText("(--:--)");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("TÂM:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("KIM GIỜ:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("KIM PHÚT:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("KIM GIÂY:");

        jLabel_KimGio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_KimGio.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_KimGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_KimGio.setText("(--:--)");

        jLabel_KimPhut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_KimPhut.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_KimPhut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_KimPhut.setText("(--:--)");

        jLabel_KimGiay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_KimGiay.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_KimGiay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_KimGiay.setText("(--:--)");

        javax.swing.GroupLayout jPanel_ThongSoDongHoLayout = new javax.swing.GroupLayout(jPanel_ThongSoDongHo);
        jPanel_ThongSoDongHo.setLayout(jPanel_ThongSoDongHoLayout);
        jPanel_ThongSoDongHoLayout.setHorizontalGroup(
            jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongSoDongHoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ThongSoDongHoLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_KimGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_KimPhut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ThongSoDongHoLayout.createSequentialGroup()
                        .addGroup(jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_KimGio, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(lbl_TAm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))))
        );
        jPanel_ThongSoDongHoLayout.setVerticalGroup(
            jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongSoDongHoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_TAm, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_KimGio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_KimPhut, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ThongSoDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_KimGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ThongSoChoiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(jPanel_Ran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_ThongSoDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ThongSoChoiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jPanel_Ran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_ThongSoDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_01;
    private javax.swing.JLabel jLabel_02;
    private javax.swing.JLabel jLabel_03;
    private javax.swing.JLabel jLabel_04;
    private javax.swing.JLabel jLabel_05;
    private javax.swing.JLabel jLabel_2;
    private javax.swing.JLabel jLabel_3;
    private javax.swing.JLabel jLabel_5;
    private javax.swing.JLabel jLabel_7;
    private javax.swing.JLabel jLabel_9;
    private javax.swing.JLabel jLabel_Boom1;
    private javax.swing.JLabel jLabel_Boom2;
    private javax.swing.JLabel jLabel_Boom3;
    private javax.swing.JLabel jLabel_Cay1;
    private javax.swing.JLabel jLabel_Cay2;
    private javax.swing.JLabel jLabel_Cay3;
    private javax.swing.JLabel jLabel_Cay4;
    private javax.swing.JLabel jLabel_Cay5;
    private javax.swing.JLabel jLabel_Cay6;
    private javax.swing.JLabel jLabel_Cay7;
    private javax.swing.JLabel jLabel_Cay8;
    private javax.swing.JLabel jLabel_DauRan;
    private javax.swing.JLabel jLabel_DiemAnDuoc;
    private javax.swing.JLabel jLabel_KimGiay;
    private javax.swing.JLabel jLabel_KimGio;
    private javax.swing.JLabel jLabel_KimPhut;
    private javax.swing.JLabel jLabel_ThucAn;
    private javax.swing.JLabel jLabel_Xe;
    private javax.swing.JPanel jPanel_Ran;
    private javax.swing.JPanel jPanel_ThongSoChoiXe;
    private javax.swing.JPanel jPanel_ThongSoDongHo;
    private javax.swing.JLabel lbl_TAm;
    // End of variables declaration//GEN-END:variables

    public void Reset() {
        timer.stop();
        timer.removeActionListener(this);
    }


    @Override
    public void actionPerformed(ActionEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (type == 0) {
            jLabel_DiemAnDuoc.setText("" + MangLuoi2D_VeConRanVersion1.diemAn);
            jLabel_DauRan.setText("(" + MangLuoi2D_VeConRanVersion1.toadoDauRan.x + ":" + MangLuoi2D_VeConRanVersion1.toadoDauRan.y + ")");
            jLabel_ThucAn.setText("(" + MangLuoi2D_VeConRanVersion1.toadoThucAn.x + ":" + MangLuoi2D_VeConRanVersion1.toadoThucAn.y + ")");
            jLabel_Boom1.setText("(" + MangLuoi2D_VeConRanVersion1.toadoBoom1.x + ":" + MangLuoi2D_VeConRanVersion1.toadoBoom1.y + ")");
            jLabel_Boom2.setText("(" + MangLuoi2D_VeConRanVersion1.toadoBoom2.x + ":" + MangLuoi2D_VeConRanVersion1.toadoBoom2.y + ")");
            jLabel_Boom3.setText("(" + MangLuoi2D_VeConRanVersion1.toadoBoom3.x + ":" + MangLuoi2D_VeConRanVersion1.toadoBoom3.y + ")");      
        }
        else if(type == 1)
        {
            
            
            jLabel_Xe.setText("("+(XeSo.x+8)+":"+(XeSo.y-7)+")"); 
            jLabel_Cay1.setText("("+trees[0].x+":"+trees[0].y+")"); 
            jLabel_Cay2.setText("("+trees[1].x+":"+trees[1].y+")"); 
            jLabel_Cay3.setText("("+trees[2].x+":"+trees[2].y+")"); 
            jLabel_Cay4.setText("("+trees[3].x+":"+trees[3].y+")"); 
            jLabel_Cay5.setText("("+trees[5].x+":"+trees[5].y+")"); 
            jLabel_Cay6.setText("("+trees[6].x+":"+trees[6].y+")"); 
            jLabel_Cay7.setText("("+trees[7].x+":"+trees[7].y+")"); 
            jLabel_Cay8.setText("("+trees[8].x+":"+trees[8].y+")"); 
        }  
        else if(type == 2)
        {
            lbl_TAm.setText("("+(Clock2d.tamDongHo.x)+":"+(Clock2d.tamDongHo.y)+")");
            jLabel_KimGio.setText("("+(Clock2d.kimGio.x)+":"+(Clock2d.kimGio.y)+")");
            jLabel_KimPhut.setText("("+(Clock2d.kimPhut.x)+":"+(Clock2d.kimPhut.y)+")");
            jLabel_KimGiay.setText("("+(Clock2d.kimGiay.x)+":"+(Clock2d.kimGiay.y)+")");
        }  
        repaint();
    }

}
