/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Shape2D;

import javax.swing.JOptionPane;

/**
 *
 * @author HUYENKUTE
 */
public class XoayConRan2D extends javax.swing.JFrame {

    /**
     * Creates new form DoiXungConRan2D
     */
    static MangLuoi2D_VeConRanVersion3 snake = new MangLuoi2D_VeConRanVersion3();;
    public XoayConRan2D() {
        initComponents();
        MangLuoi2D_VeConRanVersion3 snake = new MangLuoi2D_VeConRanVersion3();
        snake.StopRun();
        
        jPanel2D_DrawPallet.setSize(1102, 672);
        snake.setLocation(5, 5);
        snake.setSize(1102, 672);
        jPanel2D_DrawPallet.add(snake);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_BatDau = new javax.swing.JButton();
        jPanel_BangDieuKhien = new javax.swing.JPanel();
        btn_Right = new javax.swing.JButton();
        btn_Up = new javax.swing.JButton();
        btn_Left = new javax.swing.JButton();
        btn_Down = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_x = new javax.swing.JTextField();
        txt_y = new javax.swing.JTextField();
        resetTam = new javax.swing.JButton();
        jPanel2D_DrawPallet = new javax.swing.JPanel();

        setTitle("Xoay ra 9 con rắn từ 1 con rắn");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(150, 600));

        jButton_BatDau.setText("Bắt Đấu Đi");
        jButton_BatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BatDauActionPerformed(evt);
            }
        });

        jPanel_BangDieuKhien.setBackground(new java.awt.Color(102, 204, 255));
        jPanel_BangDieuKhien.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Bảng điều khiển", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btn_Right.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Right.setForeground(new java.awt.Color(204, 0, 0));
        btn_Right.setText("Phải");
        btn_Right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RightActionPerformed(evt);
            }
        });

        btn_Up.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Up.setForeground(new java.awt.Color(204, 0, 0));
        btn_Up.setText("Lên");
        btn_Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpActionPerformed(evt);
            }
        });

        btn_Left.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Left.setForeground(new java.awt.Color(204, 0, 0));
        btn_Left.setText("Trái");
        btn_Left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LeftActionPerformed(evt);
            }
        });

        btn_Down.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Down.setForeground(new java.awt.Color(204, 0, 0));
        btn_Down.setText("Xuống");
        btn_Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BangDieuKhienLayout = new javax.swing.GroupLayout(jPanel_BangDieuKhien);
        jPanel_BangDieuKhien.setLayout(jPanel_BangDieuKhienLayout);
        jPanel_BangDieuKhienLayout.setHorizontalGroup(
            jPanel_BangDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BangDieuKhienLayout.createSequentialGroup()
                .addComponent(btn_Left, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Right, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_BangDieuKhienLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel_BangDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Up, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Down))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_BangDieuKhienLayout.setVerticalGroup(
            jPanel_BangDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BangDieuKhienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Up, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BangDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Right, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btn_Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Down, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Tâm:");

        txt_x.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_x.setText("0");

        txt_y.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_y.setText("0");

        resetTam.setText("Đặt lại Tâm");
        resetTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_BangDieuKhien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_BatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(resetTam))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_x, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton_BatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetTam)
                .addGap(70, 70, 70)
                .addComponent(jPanel_BangDieuKhien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2D_DrawPalletLayout = new javax.swing.GroupLayout(jPanel2D_DrawPallet);
        jPanel2D_DrawPallet.setLayout(jPanel2D_DrawPalletLayout);
        jPanel2D_DrawPalletLayout.setHorizontalGroup(
            jPanel2D_DrawPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1097, Short.MAX_VALUE)
        );
        jPanel2D_DrawPalletLayout.setVerticalGroup(
            jPanel2D_DrawPalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2D_DrawPallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2D_DrawPallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BatDauActionPerformed
        // TODO add your handling code here:
        jPanel2D_DrawPallet.removeAll();
        snake = new MangLuoi2D_VeConRanVersion3();
        jPanel2D_DrawPallet.setSize(1102, 672);
        snake.setLocation(5, 5);
        snake.setSize(1102, 672);
        jPanel2D_DrawPallet.add(snake);
    }//GEN-LAST:event_jButton_BatDauActionPerformed

    private void btn_RightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RightActionPerformed
        // TODO add your handling code here:
        //        jPanel2D_DrawPallet.add(truc);
        snake.snake.QueoPhai();
    }//GEN-LAST:event_btn_RightActionPerformed

    private void btn_UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpActionPerformed
        // TODO add your handling code here:
        snake.snake.QueoLen();
    }//GEN-LAST:event_btn_UpActionPerformed

    private void btn_LeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LeftActionPerformed
        // TODO add your handling code here:
        snake.snake.QueoTrai();
    }//GEN-LAST:event_btn_LeftActionPerformed

    private void btn_DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DownActionPerformed
        // TODO add your handling code here:
        snake.snake.QueoXuong();
        //        snake.repaint();
    }//GEN-LAST:event_btn_DownActionPerformed

    private void resetTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTamActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(txt_x.getText()) > 100 || Integer.parseInt(txt_x.getText()) < -100 || Integer.parseInt(txt_y.getText()) > 65 || Integer.parseInt(txt_y.getText()) < -65){
                JOptionPane.showMessageDialog(null, "Gía trị x hoặc y\nkhông hợp lệ \n |x| <= 65 & |y| <= 100", "Thông báo", JOptionPane.YES_NO_OPTION);
            }
        MangLuoi2D_VeConRanVersion3.tamXoay.x =  Integer.parseInt(txt_x.getText());
        MangLuoi2D_VeConRanVersion3.tamXoay.y =  Integer.parseInt(txt_y.getText());
        snake.repaint();
    }//GEN-LAST:event_resetTamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XoayConRan2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XoayConRan2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XoayConRan2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XoayConRan2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XoayConRan2D().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Down;
    private javax.swing.JButton btn_Left;
    private javax.swing.JButton btn_Right;
    private javax.swing.JButton btn_Up;
    private javax.swing.JButton jButton_BatDau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2D_DrawPallet;
    private javax.swing.JPanel jPanel_BangDieuKhien;
    private javax.swing.JButton resetTam;
    private javax.swing.JTextField txt_x;
    private javax.swing.JTextField txt_y;
    // End of variables declaration//GEN-END:variables
}
